source: /
collections_config: {}
timezone: America/Winnipeg

paths:
  uploads: images
  static: './'

site:
  title: OdoAlibi

editor:
  # Enable CloudCannon Visual Editor
  inputs:
    hero:
      type: text
    body:
      type: html

markdown:
  engine: commonmark
